<?php

use App\Services\Reporting\Extractors;
use App\Services\Reporting\Reporting;

/**
 * Proves the PHP extractor port reproduces the standalone Express app's numbers
 * exactly. tests/Fixtures/Reporting/expected.json was generated by running the
 * real server.js extractors over the same partner files in tests/.../uploads/.
 * If a future PhpSpreadsheet/date/column-name change drifts the parsing, this
 * fails before it reaches production.
 */
$fixtureDir = __DIR__ . '/../../Fixtures/Reporting';
$uploads = $fixtureDir . '/uploads';
$expected = json_decode(file_get_contents($fixtureDir . '/expected.json'), true);
$rate = $expected['rate'];

$TOL = 1e-6;

// Map a partner name to the closure that produces its PHP per-site/day output.
$siteFile = [
    'seedtag'    => fn (string $s) => Extractors::seedtag("$uploads/SeedTag.xlsx", $s),
    'teads'      => fn (string $s) => Extractors::teads("$uploads/Teads.xlsx", $s),
    'showheroes' => fn (string $s) => Extractors::showheroes("$uploads/Showheroes.xlsx", $s),
    'gam'        => fn (string $s) => Extractors::gam("$uploads/GAM.xlsx", $s),
    'adform'     => fn (string $s) => Extractors::adform("$uploads/Adform.xlsx", $s),
    'ogury'      => fn (string $s) => Extractors::ogury("$uploads/Ogury.xlsx", $s, $rate),
];

/** Turn a list of extractor rows into [dateKey => [field => value]]. */
$perDay = function (array $rows, array $fields): array {
    $out = [];
    foreach ($rows as $r) {
        $k = Reporting::dateKey($r['date']);
        foreach ($fields as $f) $out[$k][$f] = $r[$f] ?? 0;
    }
    return $out;
};

dataset('site_partners', array_keys($siteFile));

it('matches JS output for per-site partners', function (string $partner) use ($expected, $siteFile, $perDay, $TOL) {
    $fields = $partner === 'gam' ? ['revenue'] : ['impressions', 'revenue'];

    foreach ($expected['partners'][$partner] as $site => $expDays) {
        $got = $perDay($siteFile[$partner]($site), $fields);

        expect(array_keys($got))->toEqualCanonicalizing(array_keys($expDays),
            "[$partner/$site] date keys differ");

        foreach ($expDays as $k => $vals) {
            foreach ($fields as $f) {
                expect(abs(($got[$k][$f] ?? 0) - $vals[$f]))->toBeLessThan($TOL,
                    "[$partner/$site $k] $f: got " . ($got[$k][$f] ?? 0) . " expected {$vals[$f]}");
            }
        }
    }
})->with('site_partners');

it('matches JS output for analytics (f1maximaal)', function () use ($expected, $uploads, $perDay, $TOL) {
    $fields = ['views', 'activeUsers', 'viewsPerUser', 'avgEngagement', 'eventCount', 'keyEvents', 'totalRevenue'];
    $exp = $expected['partners']['analytics']['f1maximaal'];
    $got = $perDay(Extractors::analytics(file_get_contents("$uploads/Analytics.csv")), $fields);

    expect(array_keys($got))->toEqualCanonicalizing(array_keys($exp), 'analytics date keys differ');
    foreach ($exp as $k => $vals) {
        foreach ($fields as $f) {
            expect(abs(($got[$k][$f] ?? 0) - $vals[$f]))->toBeLessThan($TOL, "[analytics $k] $f mismatch");
        }
    }
});

it('matches JS output for adhese (grouped per site)', function () use ($expected, $uploads, $TOL) {
    $domainToId = ['f1maximaal.nl' => 'f1maximaal', 'topgear.nl' => 'topgear', 'horses.nl' => 'horses', 'festileaks.com' => 'festileaks'];
    $got = [];
    foreach (scandir($uploads) as $f) {
        if (Reporting::detectFileType($f) !== 'adhese') continue;
        foreach (Extractors::adhese(file_get_contents("$uploads/$f"), $f) as $row) {
            $id = $domainToId[$row['site']] ?? null;
            if (! $id) continue;
            $k = Reporting::dateKey($row['date']);
            $got[$id][$k] = ($got[$id][$k] ?? 0) + $row['revenue'];
        }
    }

    foreach ($expected['partners']['adhese'] as $site => $expDays) {
        expect(array_keys($got[$site] ?? []))->toEqualCanonicalizing(array_keys($expDays), "[adhese/$site] date keys differ");
        foreach ($expDays as $k => $rev) {
            expect(abs(($got[$site][$k] ?? 0) - $rev))->toBeLessThan($TOL, "[adhese/$site $k] revenue mismatch");
        }
    }
});
