// Comprehensive timezone list with countries and their timezones
export const timezones = [
    // Asia
    { country: 'Afghanistan', timezone: 'Asia/Kabul', offset: '+04:30' },
    { country: 'Armenia', timezone: 'Asia/Yerevan', offset: '+04:00' },
    { country: 'Azerbaijan', timezone: 'Asia/Baku', offset: '+04:00' },
    { country: 'Bahrain', timezone: 'Asia/Bahrain', offset: '+03:00' },
    { country: 'Bangladesh', timezone: 'Asia/Dhaka', offset: '+06:00' },
    { country: 'Bhutan', timezone: 'Asia/Thimphu', offset: '+06:00' },
    { country: 'Brunei', timezone: 'Asia/Brunei', offset: '+08:00' },
    { country: 'Cambodia', timezone: 'Asia/Phnom_Penh', offset: '+07:00' },
    { country: 'China', timezone: 'Asia/Shanghai', offset: '+08:00' },
    { country: 'Cyprus', timezone: 'Asia/Nicosia', offset: '+02:00' },
    { country: 'Georgia', timezone: 'Asia/Tbilisi', offset: '+04:00' },
    { country: 'Hong Kong', timezone: 'Asia/Hong_Kong', offset: '+08:00' },
    { country: 'India', timezone: 'Asia/Kolkata', offset: '+05:30' },
    { country: 'Indonesia (Jakarta)', timezone: 'Asia/Jakarta', offset: '+07:00' },
    { country: 'Indonesia (Jayapura)', timezone: 'Asia/Jayapura', offset: '+09:00' },
    { country: 'Indonesia (Makassar)', timezone: 'Asia/Makassar', offset: '+08:00' },
    { country: 'Iran', timezone: 'Asia/Tehran', offset: '+03:30' },
    { country: 'Iraq', timezone: 'Asia/Baghdad', offset: '+03:00' },
    { country: 'Israel', timezone: 'Asia/Jerusalem', offset: '+02:00' },
    { country: 'Japan', timezone: 'Asia/Tokyo', offset: '+09:00' },
    { country: 'Jordan', timezone: 'Asia/Amman', offset: '+02:00' },
    { country: 'Kazakhstan (Almaty)', timezone: 'Asia/Almaty', offset: '+06:00' },
    { country: 'Kazakhstan (Aqtobe)', timezone: 'Asia/Aqtobe', offset: '+05:00' },
    { country: 'Kuwait', timezone: 'Asia/Kuwait', offset: '+03:00' },
    { country: 'Kyrgyzstan', timezone: 'Asia/Bishkek', offset: '+06:00' },
    { country: 'Laos', timezone: 'Asia/Vientiane', offset: '+07:00' },
    { country: 'Lebanon', timezone: 'Asia/Beirut', offset: '+02:00' },
    { country: 'Macau', timezone: 'Asia/Macau', offset: '+08:00' },
    { country: 'Malaysia', timezone: 'Asia/Kuala_Lumpur', offset: '+08:00' },
    { country: 'Maldives', timezone: 'Indian/Maldives', offset: '+05:00' },
    { country: 'Mongolia', timezone: 'Asia/Ulaanbaatar', offset: '+08:00' },
    { country: 'Myanmar', timezone: 'Asia/Yangon', offset: '+06:30' },
    { country: 'Nepal', timezone: 'Asia/Kathmandu', offset: '+05:45' },
    { country: 'North Korea', timezone: 'Asia/Pyongyang', offset: '+09:00' },
    { country: 'Oman', timezone: 'Asia/Muscat', offset: '+04:00' },
    { country: 'Pakistan', timezone: 'Asia/Karachi', offset: '+05:00' },
    { country: 'Palestine', timezone: 'Asia/Gaza', offset: '+02:00' },
    { country: 'Philippines', timezone: 'Asia/Manila', offset: '+08:00' },
    { country: 'Qatar', timezone: 'Asia/Qatar', offset: '+03:00' },
    { country: 'Russia (Moscow)', timezone: 'Europe/Moscow', offset: '+03:00' },
    { country: 'Russia (Vladivostok)', timezone: 'Asia/Vladivostok', offset: '+10:00' },
    { country: 'Russia (Yekaterinburg)', timezone: 'Asia/Yekaterinburg', offset: '+05:00' },
    { country: 'Saudi Arabia', timezone: 'Asia/Riyadh', offset: '+03:00' },
    { country: 'Singapore', timezone: 'Asia/Singapore', offset: '+08:00' },
    { country: 'South Korea', timezone: 'Asia/Seoul', offset: '+09:00' },
    { country: 'Sri Lanka', timezone: 'Asia/Colombo', offset: '+05:30' },
    { country: 'Syria', timezone: 'Asia/Damascus', offset: '+02:00' },
    { country: 'Taiwan', timezone: 'Asia/Taipei', offset: '+08:00' },
    { country: 'Tajikistan', timezone: 'Asia/Dushanbe', offset: '+05:00' },
    { country: 'Thailand', timezone: 'Asia/Bangkok', offset: '+07:00' },
    { country: 'Timor-Leste', timezone: 'Asia/Dili', offset: '+09:00' },
    { country: 'Turkey', timezone: 'Europe/Istanbul', offset: '+03:00' },
    { country: 'Turkmenistan', timezone: 'Asia/Ashgabat', offset: '+05:00' },
    { country: 'UAE', timezone: 'Asia/Dubai', offset: '+04:00' },
    { country: 'Uzbekistan', timezone: 'Asia/Tashkent', offset: '+05:00' },
    { country: 'Vietnam', timezone: 'Asia/Ho_Chi_Minh', offset: '+07:00' },
    { country: 'Yemen', timezone: 'Asia/Aden', offset: '+03:00' },

    // Europe
    { country: 'Albania', timezone: 'Europe/Tirane', offset: '+01:00' },
    { country: 'Andorra', timezone: 'Europe/Andorra', offset: '+01:00' },
    { country: 'Austria', timezone: 'Europe/Vienna', offset: '+01:00' },
    { country: 'Belarus', timezone: 'Europe/Minsk', offset: '+03:00' },
    { country: 'Belgium', timezone: 'Europe/Brussels', offset: '+01:00' },
    { country: 'Bosnia and Herzegovina', timezone: 'Europe/Sarajevo', offset: '+01:00' },
    { country: 'Bulgaria', timezone: 'Europe/Sofia', offset: '+02:00' },
    { country: 'Croatia', timezone: 'Europe/Zagreb', offset: '+01:00' },
    { country: 'Czech Republic', timezone: 'Europe/Prague', offset: '+01:00' },
    { country: 'Denmark', timezone: 'Europe/Copenhagen', offset: '+01:00' },
    { country: 'Estonia', timezone: 'Europe/Tallinn', offset: '+02:00' },
    { country: 'Finland', timezone: 'Europe/Helsinki', offset: '+02:00' },
    { country: 'France', timezone: 'Europe/Paris', offset: '+01:00' },
    { country: 'Germany', timezone: 'Europe/Berlin', offset: '+01:00' },
    { country: 'Greece', timezone: 'Europe/Athens', offset: '+02:00' },
    { country: 'Hungary', timezone: 'Europe/Budapest', offset: '+01:00' },
    { country: 'Iceland', timezone: 'Atlantic/Reykjavik', offset: '+00:00' },
    { country: 'Ireland', timezone: 'Europe/Dublin', offset: '+00:00' },
    { country: 'Italy', timezone: 'Europe/Rome', offset: '+01:00' },
    { country: 'Latvia', timezone: 'Europe/Riga', offset: '+02:00' },
    { country: 'Lithuania', timezone: 'Europe/Vilnius', offset: '+02:00' },
    { country: 'Luxembourg', timezone: 'Europe/Luxembourg', offset: '+01:00' },
    { country: 'Malta', timezone: 'Europe/Malta', offset: '+01:00' },
    { country: 'Moldova', timezone: 'Europe/Chisinau', offset: '+02:00' },
    { country: 'Monaco', timezone: 'Europe/Monaco', offset: '+01:00' },
    { country: 'Montenegro', timezone: 'Europe/Podgorica', offset: '+01:00' },
    { country: 'Netherlands', timezone: 'Europe/Amsterdam', offset: '+01:00' },
    { country: 'North Macedonia', timezone: 'Europe/Skopje', offset: '+01:00' },
    { country: 'Norway', timezone: 'Europe/Oslo', offset: '+01:00' },
    { country: 'Poland', timezone: 'Europe/Warsaw', offset: '+01:00' },
    { country: 'Portugal', timezone: 'Europe/Lisbon', offset: '+00:00' },
    { country: 'Romania', timezone: 'Europe/Bucharest', offset: '+02:00' },
    { country: 'San Marino', timezone: 'Europe/San_Marino', offset: '+01:00' },
    { country: 'Serbia', timezone: 'Europe/Belgrade', offset: '+01:00' },
    { country: 'Slovakia', timezone: 'Europe/Bratislava', offset: '+01:00' },
    { country: 'Slovenia', timezone: 'Europe/Ljubljana', offset: '+01:00' },
    { country: 'Spain', timezone: 'Europe/Madrid', offset: '+01:00' },
    { country: 'Sweden', timezone: 'Europe/Stockholm', offset: '+01:00' },
    { country: 'Switzerland', timezone: 'Europe/Zurich', offset: '+01:00' },
    { country: 'Ukraine', timezone: 'Europe/Kiev', offset: '+02:00' },
    { country: 'United Kingdom', timezone: 'Europe/London', offset: '+00:00' },
    { country: 'Vatican City', timezone: 'Europe/Vatican', offset: '+01:00' },

    // Africa
    { country: 'Algeria', timezone: 'Africa/Algiers', offset: '+01:00' },
    { country: 'Angola', timezone: 'Africa/Luanda', offset: '+01:00' },
    { country: 'Benin', timezone: 'Africa/Porto-Novo', offset: '+01:00' },
    { country: 'Botswana', timezone: 'Africa/Gaborone', offset: '+02:00' },
    { country: 'Burkina Faso', timezone: 'Africa/Ouagadougou', offset: '+00:00' },
    { country: 'Burundi', timezone: 'Africa/Bujumbura', offset: '+02:00' },
    { country: 'Cameroon', timezone: 'Africa/Douala', offset: '+01:00' },
    { country: 'Cape Verde', timezone: 'Atlantic/Cape_Verde', offset: '-01:00' },
    { country: 'Central African Republic', timezone: 'Africa/Bangui', offset: '+01:00' },
    { country: 'Chad', timezone: 'Africa/Ndjamena', offset: '+01:00' },
    { country: 'Comoros', timezone: 'Indian/Comoro', offset: '+03:00' },
    { country: 'Democratic Republic of the Congo', timezone: 'Africa/Kinshasa', offset: '+01:00' },
    { country: 'Djibouti', timezone: 'Africa/Djibouti', offset: '+03:00' },
    { country: 'Egypt', timezone: 'Africa/Cairo', offset: '+02:00' },
    { country: 'Equatorial Guinea', timezone: 'Africa/Malabo', offset: '+01:00' },
    { country: 'Eritrea', timezone: 'Africa/Asmara', offset: '+03:00' },
    { country: 'Eswatini', timezone: 'Africa/Mbabane', offset: '+02:00' },
    { country: 'Ethiopia', timezone: 'Africa/Addis_Ababa', offset: '+03:00' },
    { country: 'Gabon', timezone: 'Africa/Libreville', offset: '+01:00' },
    { country: 'Gambia', timezone: 'Africa/Banjul', offset: '+00:00' },
    { country: 'Ghana', timezone: 'Africa/Accra', offset: '+00:00' },
    { country: 'Guinea', timezone: 'Africa/Conakry', offset: '+00:00' },
    { country: 'Guinea-Bissau', timezone: 'Africa/Bissau', offset: '+00:00' },
    { country: 'Ivory Coast', timezone: 'Africa/Abidjan', offset: '+00:00' },
    { country: 'Kenya', timezone: 'Africa/Nairobi', offset: '+03:00' },
    { country: 'Lesotho', timezone: 'Africa/Maseru', offset: '+02:00' },
    { country: 'Liberia', timezone: 'Africa/Monrovia', offset: '+00:00' },
    { country: 'Libya', timezone: 'Africa/Tripoli', offset: '+02:00' },
    { country: 'Madagascar', timezone: 'Indian/Antananarivo', offset: '+03:00' },
    { country: 'Malawi', timezone: 'Africa/Blantyre', offset: '+02:00' },
    { country: 'Mali', timezone: 'Africa/Bamako', offset: '+00:00' },
    { country: 'Mauritania', timezone: 'Africa/Nouakchott', offset: '+00:00' },
    { country: 'Mauritius', timezone: 'Indian/Mauritius', offset: '+04:00' },
    { country: 'Morocco', timezone: 'Africa/Casablanca', offset: '+01:00' },
    { country: 'Mozambique', timezone: 'Africa/Maputo', offset: '+02:00' },
    { country: 'Namibia', timezone: 'Africa/Windhoek', offset: '+02:00' },
    { country: 'Niger', timezone: 'Africa/Niamey', offset: '+01:00' },
    { country: 'Nigeria', timezone: 'Africa/Lagos', offset: '+01:00' },
    { country: 'Republic of the Congo', timezone: 'Africa/Brazzaville', offset: '+01:00' },
    { country: 'Rwanda', timezone: 'Africa/Kigali', offset: '+02:00' },
    { country: 'São Tomé and Príncipe', timezone: 'Africa/Sao_Tome', offset: '+00:00' },
    { country: 'Senegal', timezone: 'Africa/Dakar', offset: '+00:00' },
    { country: 'Seychelles', timezone: 'Indian/Mahe', offset: '+04:00' },
    { country: 'Sierra Leone', timezone: 'Africa/Freetown', offset: '+00:00' },
    { country: 'Somalia', timezone: 'Africa/Mogadishu', offset: '+03:00' },
    { country: 'South Africa', timezone: 'Africa/Johannesburg', offset: '+02:00' },
    { country: 'South Sudan', timezone: 'Africa/Juba', offset: '+02:00' },
    { country: 'Sudan', timezone: 'Africa/Khartoum', offset: '+02:00' },
    { country: 'Tanzania', timezone: 'Africa/Dar_es_Salaam', offset: '+03:00' },
    { country: 'Togo', timezone: 'Africa/Lome', offset: '+00:00' },
    { country: 'Tunisia', timezone: 'Africa/Tunis', offset: '+01:00' },
    { country: 'Uganda', timezone: 'Africa/Kampala', offset: '+03:00' },
    { country: 'Zambia', timezone: 'Africa/Lusaka', offset: '+02:00' },
    { country: 'Zimbabwe', timezone: 'Africa/Harare', offset: '+02:00' },

    // North America
    { country: 'Canada (Eastern)', timezone: 'America/Toronto', offset: '-05:00' },
    { country: 'Canada (Central)', timezone: 'America/Winnipeg', offset: '-06:00' },
    { country: 'Canada (Mountain)', timezone: 'America/Edmonton', offset: '-07:00' },
    { country: 'Canada (Pacific)', timezone: 'America/Vancouver', offset: '-08:00' },
    { country: 'Canada (Atlantic)', timezone: 'America/Halifax', offset: '-04:00' },
    { country: 'Canada (Newfoundland)', timezone: 'America/St_Johns', offset: '-03:30' },
    { country: 'Mexico (Central)', timezone: 'America/Mexico_City', offset: '-06:00' },
    { country: 'Mexico (Mountain)', timezone: 'America/Chihuahua', offset: '-07:00' },
    { country: 'Mexico (Pacific)', timezone: 'America/Tijuana', offset: '-08:00' },
    { country: 'USA (Eastern)', timezone: 'America/New_York', offset: '-05:00' },
    { country: 'USA (Central)', timezone: 'America/Chicago', offset: '-06:00' },
    { country: 'USA (Mountain)', timezone: 'America/Denver', offset: '-07:00' },
    { country: 'USA (Pacific)', timezone: 'America/Los_Angeles', offset: '-08:00' },
    { country: 'USA (Alaska)', timezone: 'America/Anchorage', offset: '-09:00' },
    { country: 'USA (Hawaii)', timezone: 'Pacific/Honolulu', offset: '-10:00' },

    // South America
    { country: 'Argentina', timezone: 'America/Argentina/Buenos_Aires', offset: '-03:00' },
    { country: 'Bolivia', timezone: 'America/La_Paz', offset: '-04:00' },
    { country: 'Brazil (São Paulo)', timezone: 'America/Sao_Paulo', offset: '-03:00' },
    { country: 'Brazil (Manaus)', timezone: 'America/Manaus', offset: '-04:00' },
    { country: 'Chile', timezone: 'America/Santiago', offset: '-04:00' },
    { country: 'Colombia', timezone: 'America/Bogota', offset: '-05:00' },
    { country: 'Ecuador', timezone: 'America/Guayaquil', offset: '-05:00' },
    { country: 'French Guiana', timezone: 'America/Cayenne', offset: '-03:00' },
    { country: 'Guyana', timezone: 'America/Guyana', offset: '-04:00' },
    { country: 'Paraguay', timezone: 'America/Asuncion', offset: '-03:00' },
    { country: 'Peru', timezone: 'America/Lima', offset: '-05:00' },
    { country: 'Suriname', timezone: 'America/Paramaribo', offset: '-03:00' },
    { country: 'Uruguay', timezone: 'America/Montevideo', offset: '-03:00' },
    { country: 'Venezuela', timezone: 'America/Caracas', offset: '-04:00' },

    // Oceania
    { country: 'Australia (Sydney)', timezone: 'Australia/Sydney', offset: '+10:00' },
    { country: 'Australia (Melbourne)', timezone: 'Australia/Melbourne', offset: '+10:00' },
    { country: 'Australia (Brisbane)', timezone: 'Australia/Brisbane', offset: '+10:00' },
    { country: 'Australia (Perth)', timezone: 'Australia/Perth', offset: '+08:00' },
    { country: 'Australia (Adelaide)', timezone: 'Australia/Adelaide', offset: '+09:30' },
    { country: 'Australia (Darwin)', timezone: 'Australia/Darwin', offset: '+09:30' },
    { country: 'Fiji', timezone: 'Pacific/Fiji', offset: '+12:00' },
    { country: 'New Zealand', timezone: 'Pacific/Auckland', offset: '+12:00' },
    { country: 'Papua New Guinea', timezone: 'Pacific/Port_Moresby', offset: '+10:00' },
    { country: 'Solomon Islands', timezone: 'Pacific/Guadalcanal', offset: '+11:00' },
    { country: 'Vanuatu', timezone: 'Pacific/Efate', offset: '+11:00' },

    // UTC
    { country: 'UTC', timezone: 'UTC', offset: '+00:00' }
];

// Helper function to get timezone by country
export const getTimezoneByCountry = (country) => {
    return timezones.find(tz => tz.country.toLowerCase().includes(country.toLowerCase()));
};

// Helper function to search timezones
export const searchTimezones = (query) => {
    const lowerQuery = query.toLowerCase();
    return timezones.filter(tz => 
        tz.country.toLowerCase().includes(lowerQuery) ||
        tz.timezone.toLowerCase().includes(lowerQuery) ||
        tz.offset.includes(lowerQuery)
    );
};

// Get default timezone (Asia/Dhaka)
export const getDefaultTimezone = () => {
    return timezones.find(tz => tz.timezone === 'Asia/Dhaka') || timezones[0];
};

export default {
    timezones,
    getTimezoneByCountry,
    searchTimezones,
    getDefaultTimezone
};